### ISSUE TITLE
Not working for BitBucket

### ISSUE THREAD

**Issue by ericbiewener** [gerep/git-open#13]
It's opening the url `https://bitbucket.org/https://ericbiewener@bitbucket/branch/master`, which isn't valid.

**Comment by gerep** [comment]
Hi @ericbiewener I'm sorry but I didn't receive any notifications when you opened this issue, I will take a look at it and update you

**Comment by gerep** [comment]
Hello again @ericbiewener. I understand the problem with the URL but I can't think of any test to replicate this situation, can you please give me more details?

**Comment by ericbiewener** [comment]
Sorry for the delayed response, I've been traveling. When I run `git remote -v`, I get the following:
```
origin	https://ericbiewener@bitbucket.org/ericbiewener/write.git (fetch)
origin	https://ericbiewener@bitbucket.org/ericbiewener/write.git (push)
```
It's a private repo. Beyond that, I'm not sure of what other details I can provide. I'm in the root of my project when I enter `git open`, and it sends me to the URL I originally posted.

**Comment by gerep** [comment]
Hi @ericbiewener thank you for the valuable information.

I have commited a fix, can you please test?

=)

**Comment by ericbiewener** [comment]
That does it! Nice work!
